---
development:
  cloud_name: dar1oti2e
  api_key: '486493313578966'
  api_secret: eb7FhJndYV3nHjcoE8efOKO9UO8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dar1oti2e
  api_key: '486493313578966'
  api_secret: eb7FhJndYV3nHjcoE8efOKO9UO8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dar1oti2e
  api_key: '486493313578966'
  api_secret: eb7FhJndYV3nHjcoE8efOKO9UO8
  enhance_image_tag: true
  static_image_support: false
